### ISSUE TITLE
Provide legend

### ISSUE THREAD

**Issue by claczny** [claczny/VizBin#13]
Provide a "Menu" entry that allows to visualize a legend, probably in a separate window which then pops up.

**Comment by fwhelan** [comment]
Should the legend appear as a default when an annotation file is provided? Or does the user have to request it in some way (I can't find anything in the File menu).

**Comment by claczny** [comment]
No, the legend does not appear by default.
You can make it visible by right-clicking on the scatter plot which will open a menu.

We have observed a little issue with the legend: For some reason, points that are drawn as filled circles in the plots, are represented as small, filled rectangles.
This can cause some confusion as the rectangle itself is a possible symbol, which would however appear to be larger in size, s.a., #22.

**Comment by fwhelan** [comment]
Awesome, thanks! May I humbly suggest that this is added to the wiki tutorial page?

**Comment by claczny** [comment]
Sure.

I just checked it and while there is some "hint" in https://github.com/claczny/VizBin/wiki/Tutorial in the picture illustrating the point "Clicking the right mouse button (anywhere within the visualization) will open a menu where you can choose to export your selection. A confirmation window will apear.", it is way too subtle and nowhere explained explicitly.

Hence, it will be included into the wiki as part of the next update (s.a. issue #30).
