### ISSUE TITLE
Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by yoyohashao** [claczny/VizBin#32]
Hello, I was gonna open a newly saved workspace but then this happened:
![image](https://cloud.githubusercontent.com/assets/7657231/10076171/9b22d0b6-630c-11e5-9035-b237537e3e5d.png)
I didn't encounter any problem to open a saved workspace last night though.
Also I found the size of workspace was smaller when using kmer=5 than that when kmer=4

**Comment by claczny** [comment]
Interesting error and thanks for reporting it.

Did you wait to terminate the VizBin application until a "File saved successfully" was displayed when you originally saved the respective workspace?
You could also try to  unzip the workspace with the unzip-program of your choice and see if this works or if the zip-file might be damaged.

> Also I found the size of workspace was smaller when using kmer=5 than that when kmer=4

Could you maybe provide some more information, such as what the difference in filesize is?
Also, do you refer to the workspace that can be loaded and a workspace which can not be loaded?

**Comment by yoyohashao** [comment]
I think the problem is caused by incomplete saving procedure. I mis-stated the size difference as when kmer=5 it's bigger (57MB vs. 32MB). But that 32MB could be due to the workspace wasn't fully saved

**Comment by claczny** [comment]
Great. I consider this issue closed then.
